import turtle

a = 5
print(a)
b = "hello"
print(b)
credit_card = 44443333222211111
print(credit_card)

rosh_turtle = turtle.Turtle()


def square():
    #rosh_turtle=turtle.Turtle()
    rosh_turtle.forward(100)
    rosh_turtle.right(90)
    rosh_turtle.forward(100)
    rosh_turtle.right(90)
    rosh_turtle.forward(100)
    rosh_turtle.right(90)
    rosh_turtle.forward(100)


square()
rosh_turtle.forward(200)
